### ISSUE TITLE
[bug] GitHub account is missing country and location information.

### ISSUE THREAD

**Issue by ydFu** [cncf/devstats#1]
# Problem description:
When using the following search, I found that my contributions are not included in the country statistics.

1. My contributions cannot be found.
- github: ydFu
- country: Taiwan

https://k8s.devstats.cncf.io/d/66/developer-activity-counts-by-companies?orgId=1&var-period_name=Last%20decade&var-metric=contributions&var-repogroup_name=All&var-repo_name=kubernetes%2Fkubernetes&var-country_name=Taiwan%20Province%20of%20China&var-companies=All

![image](https://user-images.githubusercontent.com/64598482/232720891-865247eb-bac8-45b3-a105-e8a29f78e7a9.png)

---
2. But my contributions are included in "all".

- github: ydFu
- country: All

https://k8s.devstats.cncf.io/d/66/developer-activity-counts-by-companies?orgId=1&var-period_name=Last%20decade&var-metric=contributions&var-repogroup_name=All&var-repo_name=kubernetes%2Fkubernetes&var-country_name=All&var-companies=All

![image](https://user-images.githubusercontent.com/64598482/232724232-0599331e-089f-41ec-a394-4ca640629316.png)

# Possible reasons:
Currently, when checking my data in `github_users.json`, I found that the fields "country_id" and "location" are missing

github_users.json
https://github.com/cncf/devstats/blob/master/github_users.json

![image](https://user-images.githubusercontent.com/64598482/232726168-3fde1a51-822b-43fc-92a5-3d7d5e959ff2.png)

# Bug fix.
I hope that I can adjust the settings according to my own country on GitHub,And anyone can search for country-specific categories of related metrics within `k8s.devstats.cncf.io`.

- github: ydFu
"location": "Taipei, Taiwan"
"country_id": "tw"

![image](https://user-images.githubusercontent.com/64598482/232727041-cb4ba99d-13a4-49de-9a48-65a31d9766ad.png)

**Comment by lukaszgryglicki** [comment]
I will do this fix next week.

**Comment by lukaszgryglicki** [comment]
Updated JSON, please note that changes will be visible when the newest affiliations are imported (which happens once per 4 weeks).

**Comment by Seo-yul** [comment]
@lukaszgryglicki
What happens when there is no information in the file?
I became a member of Kubernetes last year, but there is no information in this `github_users.json` file.

**Comment by lukaszgryglicki** [comment]
Please add your data in `cncf/gitdm` following [this](https://github.com/cncf/gitdm#addingupdating-affiliation) so you data will be added in post-merge scripts.

**Comment by Seo-yul** [comment]
I will check that page
Thank you so much.
