### ISSUE TITLE
[bug]TOC devstats lost past statistical data

### ISSUE THREAD

**Issue by renyunkang** [cncf/devstats#10]
When we were writing `OpenELB 2022 Annual Review`, we found that devstats did not count the relevant data of openelb's github in 2022. Can you tell us the reason? Maybe we're missing something.

Here is the link to devstats：[Activity Repository Groups](https://openelb.devstats.cncf.io/d/1/activity-repository-groups?orgId=1&from=now-2y&to=now)
Projects: https://github.com/openelb/openelb
Issue: https://github.com/openelb/openelb/issues/333

**Comment by lukaszgryglicki** [comment]
My blind shot would be that OpenELB moved to a separate GitHub org but didn't inform me, so I wasn't trackign it for some time, I will try to take a look as soon as possible - maybe I can make it today, if not - I'll do this on Monday (we have a long weekend starting from Thu and I'll be on vacation).

**Comment by lukaszgryglicki** [comment]
I'm backfilling data starting from 2021-10-09 and then I'll regenerate all dashboards.

**Comment by lukaszgryglicki** [comment]
BTW: areound 10/20/21 there was a big outage in GitHub archives that affected most of projects, but it was fixed in a week or two, so some data `may be` missing and there is nothign I can do, but not THAT amount of data which was reported here, investigating.

**Comment by lukaszgryglicki** [comment]
Repo movement to `openelb` was around `2021-12-13` and then I was not informed about this, probably data gap is becaus eof that - trhen a lot later somebody informed me and I added `openelb` org to track (I cannot follow 150+ projects every day) so there is a gap - but I will backfill it now. We also have devstats-landscape sync cron now [see here](https://github.com/cncf/devstats-landscape-sync) so if at least landscape is updated with new repo/org configuration I'm getting an email and updating DevStats asap.
```
org,repo,rid,oid,date_from,date_to
kubesphere,kubesphere/porter,168629414,37326490,2019-02-01 02:21:19,2021-03-08 10:26:38
kubesphere,kubesphere/porterlb,168629414,37326490,2021-03-11 03:20:30,2021-07-06 03:01:07
kubesphere,kubesphere/openelb,168629414,37326490,2021-07-06 07:12:52,2021-12-13 12:27:52
openelb,openelb/openelb,168629414,86996287,2021-12-13 16:49:52,2023-05-30 22:58:12
```

**Comment by lukaszgryglicki** [comment]
This is fixed, see [the dashboard](https://openelb.devstats.cncf.io/d/1/activity-repository-groups?orgId=1&from=now-2y&to=now).
<img width="2351" alt="Zrzut ekranu 2023-06-6 o 12 24 49" src="https://github.com/cncf/devstats/assets/2469783/1ac33000-a60b-4271-90e2-8b4ba33631e4">

cc @renyunkang @caniszczyk
