### ISSUE TITLE
[bug] Wrong link to projects stat dashboard

### ISSUE THREAD

**Issue by khanhtc1202** [cncf/devstats#11]
All five newly added projects stat dashboard links are showing wrong in https://devstats.cncf.io/  board. Instead of `project.devstats.cncf.io` (as of other projects) currently, the link available there is `project.teststats.cncf.io`. 

Is that a configuration missed or still in the middle of configuring process?

**Comment by lukaszgryglicki** [comment]
It's a bug, will TAL.

**Comment by lukaszgryglicki** [comment]
Fixed.
