### ISSUE TITLE
[bug] Project logo does not show in devstat dashboard

### ISSUE THREAD

**Issue by khanhtc1202** [cncf/devstats#12]
Hi @lukaszgryglicki, thanks so much for your quick response 🙏 

My PR to artwork has already been merged (ref https://github.com/cncf/artwork/pull/411) but the project logo does not show in the devstat dashboard, do I need any further config/commit to make it?

**Comment by lukaszgryglicki** [comment]
I will update the artwork (if I have both SVG and PNG) on Friday. I can't work on this earlier.
Merging artwork PR does not automagically mean the logo is updated in DevStats.

**Comment by khanhtc1202** [comment]
I see, thank you 🙏

**Comment by lukaszgryglicki** [comment]
On it.

**Comment by lukaszgryglicki** [comment]
https://devstats.cncf.io and https://testsstats.cncf.io already updated, all Grafana instances are being updated now.

**Comment by lukaszgryglicki** [comment]
All Grafanas updated as well (bot `test` instances and `prod` instances).
