### ISSUE TITLE
bug - Set contributions retroactively for pasha-codefresh

### ISSUE THREAD

**Issue by todaywasawesome** [cncf/devstats#13]
@pasha-codefresh started contributing to the Argo Project in 2021 but didn't have affiliation set until 2022. Can we retroactively attribute his contributions back to Jan 2021? It should be associated with Codefresh.

**Comment by lukaszgryglicki** [comment]
Create a PR against `cncf/gitdm` repo - once merged it will be imported in every CNCF project withing up to 4 weeks time window (including past).
