### ISSUE TITLE
Company Statistics by Repostory Group is down

### ISSUE THREAD

**Issue by jberkus** [cncf/devstats#17]
[bug]

This chart isn't displaying:

https://k8s.devstats.cncf.io/d/8/company-statistics-by-repository-group?orgId=1

Haven't been able to figure out why.  It went offline less than 2 weeks ago.

**Comment by lukaszgryglicki** [comment]
I will fix this tomorrow.

**Comment by lukaszgryglicki** [comment]
On it.

**Comment by lukaszgryglicki** [comment]
This is fixed @jberkus closing, thanks for reporting.
