### ISSUE TITLE
Fetch data from renamed Knative GitHub Organization

### ISSUE THREAD

**Issue by upodroid** [cncf/devstats#19]
Hello

I'm the Knative Productivity Working Group Lead and we recently renamed one of our GitHub organizations from knative-sandbox to knative-extensions.

Please update the scripts that fetch data from GitHub to reference the new org.

https://github.com/cncf/devstats/blob/master/projects.yaml#L1696
https://github.com/knative-sandbox
https://github.com/knative-extensions
https://github.com/knative/community/issues/169

@lukaszgryglicki

**Comment by lukaszgryglicki** [comment]
I will work on this on Monday.

**Comment by lukaszgryglicki** [comment]
On it. There will be more files to change in more repos - but I will handle all of this and update here. I will also figure out when this new org was added and will backfill the past data + regenerate TSDB/all stats.

**Comment by lukaszgryglicki** [comment]
This is done, closing.

**Comment by upodroid** [comment]
Thanks
