### ISSUE TITLE
[feature request] Use new logo for CNCF devstats

### ISSUE THREAD

**Issue by cjyabraham** [cncf/devstats#2]
To align more closely with the CNCF brand, could you use the attached logo for https://devstats.cncf.io/ ?

![devstats-logo](https://user-images.githubusercontent.com/463160/232821489-0332269a-5f35-459b-9ea6-9ad922e99eda.svg)

This has been [okayed by Chris Aniszczyk](https://github.com/cncf/cncf.io/issues/717#issuecomment-1512486341)

**Comment by cjyabraham** [comment]
PNG version:
![devstats-logo](https://user-images.githubusercontent.com/463160/232822526-78fa4dc8-ee84-4e9c-9725-428d14859ac7.png)

**Comment by lukaszgryglicki** [comment]
Hmm, this is not the square logo used everywhere, can you please let me know where exactly should I change that logo?

**Comment by lukaszgryglicki** [comment]
I'm going to update the bottom devstats link (the one before `Hardware for this site is graciously donated by`) and favicon. In other places we also use the CNCF logo but when referring to a project that doesn't have an artwork icon yet - but in this case it is not DevStats as such but "unknown logo CNCF project" so I assume it should use normal CNCF icon, correct me if I'm wrong.

**Comment by lukaszgryglicki** [comment]
Closing, please let me know if I should update that icon in other places, and if so then please let me know where exactly. The icon is added to a build process for DevStats images, so can be updated wherever needed.
cc @caniszczyk @cjyabraham

**Comment by cjyabraham** [comment]
@lukaszgryglicki can you put the logo to match this?
<img width="1440" alt="Screen Shot 2023-04-24 at 12 31 44 PM" src="https://user-images.githubusercontent.com/463160/233907828-680aac51-8564-4994-ace7-a1fdd66b9967.png">

**Comment by lukaszgryglicki** [comment]
OK will do.

**Comment by lukaszgryglicki** [comment]
Done.
