### ISSUE TITLE
[bug] Incorrect country mapping for my user

### ISSUE THREAD

**Issue by ahurtaud** [cncf/devstats#22]
Hello,

We are using the [devstats dashboard at my company](https://all.devstats.cncf.io/d/55/company-prs-in-repository-groups-table?orgId=1&var-period_name=Last%20decade&var-repogroups=All&var-companies=Amadeus&var-countries=All) and I saw that for my user (ahurtaud) the country is Albania and I would like to fix it for France.

I have tried to add my France location in my GH profile but my latest contribution to opentelemetry is still flagged as Albania.

Digging into the different repositories I found https://github.com/search?q=repo%3Acncf%2Fgitdm%20hurtaud&type=code
And I found only this trickster csv file which may have incorrect country column set as `al`: https://github.com/cncf/gitdm/blob/eb68b9621183a91c2756f034d8969e6c9c73a024/src/trickster_task.csv#L47.

Is manually doing a PR to this file would be the "correct" way to fix the country or any other solution?

Thank you
Alban

**Comment by lukaszgryglicki** [comment]
I will fix this in the `github_users.json` file, but I can only do that next week. I will update you then.

**Comment by lukaszgryglicki** [comment]
This is updated, data will be updated in the dashboard when the next `All CNCF` affiliations import runs which is:
```
root@devstats-node-0:~/cncf/devstats-helm# k get cj | grep -E 'affiliations-all'
devstats-affiliations-all                       0 8 27 * *                               False     0        20d             2y236d
```
27th August at 8:00 AM UTC.
