### ISSUE TITLE
[bug] users not associated with company

### ISSUE THREAD

**Issue by waldirmontoya25** [cncf/devstats#24]
The following [dashboard](https://backstage.devstats.cncf.io/d/66/developer-activity-counts-by-companies?orgId=1) does not show the users `waldirmontoya25`, `luchillo17`, `jamieklassen` and `rubenv-dev`, associated with a company. We created the PR to update the association and I see the proper values in [this file](https://github.com/cncf/devstats/blob/master/github_users.json).

Thanks a lot for any guidance if I'm missing something.

**Comment by lukaszgryglicki** [comment]
I will take a look at Friday, possibly new affiliations weren't imported yet - this happens once per 28 days (4 weeks). I will also check JSON for those users and their affiliations and report here. I'll do this with a batch of other PRs for `cncf/gitdm` as there are many because I just returned from the PTO/vacation.

**Comment by lukaszgryglicki** [comment]
So, I have the following correct entries in JSON:
```
  {
    "login": "waldirmontoya25",
(...)
    "affiliation": "Independent < 2015-04-01, VMware Inc.",
    "source": "user",
    "name": "Waldir Montoya",
    "commits": 41
  },
(...)
  {
    "login": "jamieklassen",
(...)
    "affiliation": "Independent < 2016-09-06, Pivotal < 2017-11-01, CGI < 2018-05-01, Pivotal < 2020-04-06, VMware Inc.",
    "source": "user",
    "name": "Jamie Klassen",
    "commits": 334
  },
(...)
  {
    "login": "RubenV-dev",
(...)
    "affiliation": "Independent < 2021-07-26, VMware Inc.",
    "source": "user",
    "name": "Ruben Vallejo",
    "commits": 126,
    "location": "New York,NY",
    "country_id": "us"
  },
```

This user has no affiliation (`?`) - I can add it if you provide it for me, even here as a comment:
```
  {
    "login": "luchillo17",
(...)
    "affiliation": "?",
    "name": "Carlos Esteban Lopez Jaramillo",
    "commits": 356,
    "location": "Colombia",
    "country_id": "co"
  },
```

For now, I will just change to `VMware Inc.`.
I will reimport affiliations manually after I finish some other PRs, so you should see the changes immediately. I'll update here.

**Comment by lukaszgryglicki** [comment]
Data is already fixed, now I will reimport affs for Backstage.

**Comment by lukaszgryglicki** [comment]
Data imported, all requested users now show [on this dashboard](https://backstage.devstats.cncf.io/d/66/developer-activity-counts-by-companies?orgId=1&var-period_name=Last%20decade&var-metric=contributions&var-repogroup_name=All&var-country_name=All&var-companies=VMware%20Inc.), closing.

**Comment by waldirmontoya25** [comment]
thank you so much @lukaszgryglicki
