### ISSUE TITLE
Change company affiliation for Vitess contributors

### ISSUE THREAD

**Issue by deepthi** [cncf/devstats#27]
For the following users:
@maxenglander - PlanetScale starting June 28, 2022
@GuptaManan100 - PlanetScale. Both current affiliations (SAP and Cisco) are incorrect.

**Comment by lukaszgryglicki** [comment]
PLS create a PR against `cncf/gitdm` following [this](https://github.com/cncf/gitdm#addingupdating-affiliation) or LMK that you can't do it and want me to update manually instead - the I will do this on Friday.

**Comment by deepthi** [comment]
I can create a PR, thanks!

**Comment by GuptaManan100** [comment]
Here is the PR - https://github.com/cncf/gitdm/pull/154

**Comment by lukaszgryglicki** [comment]
Will work on this tomorrow, I'm closing this issue then.
