### ISSUE TITLE
[feature request] Support multi-select of repositories under Repository Group

### ISSUE THREAD

**Issue by xtreme-sameer-vohra** [cncf/devstats#28]
# Context
[Knative ](https://knative.dev/) is composed of 3 distinct domains (Serving, Eventing & Functions). It would be valuable to be able to easily view & aggregate metrics for each of these individually. 

For example, on the [Contributors Chart](https://knative.devstats.cncf.io/d/74/contributions-chart?orgId=1&var-period=m&var-metric=contributions&var-repogroup_name=All&var-country_name=All&var-company_name=All&var-company=all), one can select "All" to get data for the entire community or a single repository at a time. 

If I wanted to understand the contributors to the Serving domain, I'd want to aggregate stats for

- knative/serving
- knative/serving-operator
- knative/networking
- knative-extenstions/net-istio
- knative-extenstions/net-certmanager
- knative-extenstions/net-contour
- knative-extenstions/net-kourier
- .....

Aggregating the data for each repo (eg. add contributors for knative/serving +  knative/serving-operator+...) would not be an accurate representation as individuals that work on multiple repos would be counted more than once.

**Comment by lukaszgryglicki** [comment]
I'll be on PTO until Sep 11th, I can take a look then.
But you can define so-called `Repository groups` and have all-dashboards-wide definitions of some special `groups`.

By default in each CNCF project `repository group` = `every single repo`.

But you can say: define the `Serving` repository group as every repo that belongs to the `knative-serving` org or by just listing repos that should be there, then define another repository group for the next set, and so on.

If you provide such a list of which repo should belong to which repository group - it will support your request out of the box and I will manage to do it before my PTO 9which starts 31st of August).

**Comment by lukaszgryglicki** [comment]
Something similar to Kubernetes SIGs definitions as repository groups: https://github.com/cncf/devstats/blob/master/scripts/kubernetes/repo_groups.sql

Currently `knative` uses default fallback: https://github.com/cncf/devstats/blob/master/scripts/shared/repo_groups.sql, while you can define your custom ones in https://github.com/cncf/devstats/blob/master/scripts/knative/repo_groups.sql.

More details about repo groups: https://github.com/cncf/devstats/blob/master/docs/repository_groups.md

**Comment by lukaszgryglicki** [comment]
@xtreme-sameer-vohra ?

**Comment by lukaszgryglicki** [comment]
Please define the requested repo groups, this will solve this issue IMHO.

**Comment by lukaszgryglicki** [comment]
DevStats now also supports org wide repo groups (GitHub org as a repository group),more details [here](https://github.com/cncf/devstats/discussions/32).

I'm closing this due to inactivty, all what is needed is to provide requested repository groups definition - eiather as a PR or describe it like (repos X, Y, Z belong to repo group A, repos P, Q, R belong to repo group B, and so on). In either case I will update.

Closing this.
