### ISSUE TITLE
[help needed] repository was migrated from `alibaba/sealer` to `sealerio/sealer`

### ISSUE THREAD

**Issue by kakaZhou719** [cncf/devstats#3]
hello teams,

i am from sealer (https://github.com/sealerio/sealer) community,  our project `sealer` is under CNCF now. 

Unfortunately, we can not see any devstats data from the DevStats dashboard , is there something additional configuration for our project?

![image](https://user-images.githubusercontent.com/83740799/233010160-620f22dc-8a66-4944-a9f8-f75077f3f377.png)

below is  devstats link:
https://sealer.devstats.cncf.io/d/8/dashboards?orgId=1&refresh=15m

looking forward to your reply, thanks in advance .

**Comment by kakaZhou719** [comment]
hi @lukaszgryglicki, our repository was migrated from `alibaba/sealer` to `sealerio/sealer` last year. is this the reason why we see blank devstats data? and how can we adjust this change?

FYI:
 https://github.com/cncf/devstats/blob/a0fb08fdf1a4d91488d88bf70d4a4589b8a1a3e5/sealer/psql.sh#L16

**Comment by lukaszgryglicki** [comment]
The reason for this is very simple, I wasn't informed about this at the time when it happened, so the new GitHub org is not tracked. I will update config and reprocess past data to add this. I will do this next week, necause I'm on KubeCon this week.

**Comment by lukaszgryglicki** [comment]
On it.

**Comment by lukaszgryglicki** [comment]
Done, data refetched from 4/29/2022 when org was moved, then TSDB data regenerated and projects health metrics also updated, see:
- https://sealer.devstats.cncf.io/d/8/dashboards?orgId=1&refresh=15m
- https://sealer.devstats.cncf.io/d/1/activity-repository-groups?orgId=1
- https://all.devstats.cncf.io/d/54/project-health-table?orgId=1&var-repogroup_name=sealer
- https://all.devstats.cncf.io/d/53/projects-health-table?orgId=1

Closing, please reopen if needed.
