### ISSUE TITLE
[bug] Kubernetes `company-statistics-by-repository-group` page does not load

### ISSUE THREAD

**Issue by dims** [cncf/devstats#30]
URL : https://k8s.devstats.cncf.io/d/8/company-statistics-by-repository-group?orgId=1

Error screen shot(s):
![image](https://github.com/cncf/devstats/assets/23304/53533262-2829-4e12-8c5a-d42998918636)

![image](https://github.com/cncf/devstats/assets/23304/647869ec-379e-4b58-984e-780b877bc6bb)

The dashboard across all CNCF projects seems to work fine - https://all.devstats.cncf.io/d/4/company-statistics-by-repository-group?orgId=1

**Comment by lukaszgryglicki** [comment]
I'm on PTO, but checking this.

**Comment by lukaszgryglicki** [comment]
Fixed, closing this, thanks for reporting.
