### ISSUE TITLE
[feature request] Add a dashboard for the CNCF GH Org

### ISSUE THREAD

**Issue by jeefy** [cncf/devstats#31]
We don't actually track or monitor (using devstats) contributions to the CNCF GitHub org itself. This request has come up several times recently, and it seems like a no brainer. :)

**Comment by lukaszgryglicki** [comment]
We do (only on the test instance with some test-only stuff): https://cncf.teststats.cncf.io/d/8/dashboards?orgId=1&refresh=15m

Closing as complted.
cc @jeefy

**Comment by lukaszgryglicki** [comment]
Just ignore some missing panels and dashboards called like `xyz ES` or `Home`, `Home 2` - this is an internal test instance, but perfectly usable also cc @caniszczyk

**Comment by AudMonte01** [comment]
It would be great to be able to select all CNCF Org-related items in the "repository group" drop-down here: https://cncf.teststats.cncf.io/d/50/countries-statistics-in-repository-groups?orgId=1

**Comment by lukaszgryglicki** [comment]
Added to my TODO, ETA is after KubeCon China - there are also 5 new CNCF projects that I need to add first. So it will be done, but you need to wait a bit, I'm very sorry :(

**Comment by lukaszgryglicki** [comment]
Done: https://cncf.teststats.cncf.io/d/50/countries-statistics-in-repository-groups?orgId=1
Now you can select full orgs from the repository drop-dow - `cncf` is one of them.
Closing as completed.

cc @caniszczyk

**Comment by AudMonte01** [comment]
Thank you, @lukaszgryglicki ! Do you know if someone contributes to the Glossary, if this will be accounted for in the DevStats under "Contributor"?

**Comment by lukaszgryglicki** [comment]
It should, but give me an example of such contribution and I can track it down after the KubeCon China.

**Comment by AudMonte01** [comment]
Unfortunately I don't have an example, but I see that the Glossary work is done in GitHub, so that is reassuring. :-)

**Comment by lukaszgryglicki** [comment]
I'll take a look on Monday.

**Comment by lukaszgryglicki** [comment]
Other dashboards now also have an option to choose full `org` from GitHub as a repo group - so now a list of repo groups contains all repos and all orgs - all dashboards wide and adding the same in other DevStats instances. I will address [this](https://github.com/cncf/devstats/issues/31#issuecomment-1737975194) when I'm back from China.

**Comment by lukaszgryglicki** [comment]
Regarding [this question](https://github.com/cncf/devstats/issues/31#issuecomment-1737975194) - yes, this is an example dashboard that shows the number of contributors and contributions in `cncf/glossary`:  [click](https://cncf.teststats.cncf.io/d/74/contributions-chart?orgId=1&var-period=m&var-metric=contributions&var-repogroup_name=cncf%2Fglossary&var-country_name=All&var-company_name=All&var-company=all), another [example](https://cncf.teststats.cncf.io/d/9/developer-activity-counts-by-repository-group-table?orgId=1&var-period_name=Last%20decade&var-metric=contributions&var-repogroup_name=cncf%2Fglossary&var-country_name=All) shows per-contributor contributions stats in `cncf/glossary` repo.

**Comment by AudMonte01** [comment]
Oooo, this [example](https://cncf.teststats.cncf.io/d/9/developer-activity-counts-by-repository-group-table?orgId=1&var-period_name=Last%20decade&var-metric=contributions&var-repogroup_name=cncf%2Fglossary&var-country_name=All) that shows per-contributor contributions stats in cncf/glossary repo is helpful!
