### ISSUE TITLE
"invalid-email-address" is the #6 contributor to Linkerd

### ISSUE THREAD

**Issue by craigbox** [cncf/devstats#34]
https://linkerd.devstats.cncf.io/d/66/developer-activity-counts-by-companies?orgId=1&var-period_name=Last%20decade&var-metric=commits&var-repogroup_name=All&var-country_name=All&var-companies=All

<img width="1244" alt="Screenshot 2023-10-01 at 10 06 32 PM" src="https://github.com/cncf/devstats/assets/132510/2013cc77-fd50-441a-be61-8b6b4aea56cd">

[This may be related](https://stackoverflow.com/questions/39287680/invalid-email-address-on-github) to how GitHub dealt with empty email addresses in commits or imports long time ago; I don't think they display in this fashion today.

Could devstats filter these commits somehow?

**Comment by lukaszgryglicki** [comment]
Yes, I can mark them as invalid, will investigate to confirm and do this on Monday.

**Comment by lukaszgryglicki** [comment]
Done, thanks for reporting.
