### ISSUE TITLE
[feature request] add PR reviews category to dashboards

### ISSUE THREAD

**Issue by deepthi** [cncf/devstats#35]
Currently devstats solely tracks PR authors and show PR author contributions by Company etc.
A big part of project maintainer work is PR reviews. In fact, security guidelines require _two_ reviews per pull request before it can be accepted. These contributions are currently being ignored by devstats. Code review is also development work, and should be captured.

**Comment by lukaszgryglicki** [comment]
Reviews are being counted as contributions, where do you think they are ignored? Can you point me to some examples - if they are ignored, then this is a bug and I will fix it.

**Comment by lukaszgryglicki** [comment]
@deepthi ping - where / which dashboard - reviews are ignored?

**Comment by lukaszgryglicki** [comment]
Closing this because a got no additional feedback, please reopen if needed.

**Comment by deepthi** [comment]
You are right, I explored the dashboards and found where they are counted.
Thanks! Great work.
