### ISSUE TITLE
k8s devstats score is not updated

### ISSUE THREAD

**Issue by atoato88** [cncf/devstats#39]
I'm not sure about this is a bug, it's just a question.

Recently the scores on k8s.devstats.cncf.io have been not updated.
I checked [the page "Last updated"](https://k8s.devstats.cncf.io/d/82/last-updated?orgId=1) to find the timestamps for the last updates.
It seems that most recent timestamp is 2023/10/02, it's approximately two weeks ago.

Is there an issue with the website?

**Comment by lukaszgryglicki** [comment]
It should update more often but this depends on particular dashboard and time range, so pls LMK which dashboard and time range.

Simple example - dashboards that aggregate monthly need only to update once a month, those daily -0 shoudl update at elast once a day, and those yearly can update once a year and so on. This is not that simple in details but I'm a bit generalizing here, so please LMK which exact dashboard - provide a link or screenshot.

Thanks.

**Comment by atoato88** [comment]
I check the dashboards followings:
- [Contributions on Companies table](https://k8s.devstats.cncf.io/d/9/companies-table?orgId=1&var-period_name=v1.28.0%20-%20now&var-metric=contributions)
- [Contributions on Developer Activity Counts by Companies](https://k8s.devstats.cncf.io/d/66/developer-activity-counts-by-companies?orgId=1&var-period_name=v1.28.0%20-%20now&var-metric=contributions&var-repogroup_name=All&var-country_name=All&var-companies=All&var-repo_name=kubernetes%2Fkubernetes)
- [PRs on Developer Activity Counts by Companies](https://k8s.devstats.cncf.io/d/66/developer-activity-counts-by-companies?orgId=1&var-period_name=v1.28.0%20-%20now&var-metric=prs&var-repogroup_name=All&var-country_name=All&var-companies=All&var-repo_name=kubernetes%2Fkubernetes)

Time range I usually check is the latest k8s development cycle, so it's `v1.28.0 - now` (means v1.29.0 cycle) for now.

Thank you for quick comment.

**Comment by lukaszgryglicki** [comment]
Will check how often this refreshes - to be honest I don't remember atm, will check on Friday at the latest.

**Comment by lukaszgryglicki** [comment]
On it.

**Comment by lukaszgryglicki** [comment]
I see where issue is, regenerating data and restarting the syncer which failed due to outage of `kubelet` diskspace that I've fixed a few days ago but I forget to set the `provisioned` flag on one database.

**Comment by lukaszgryglicki** [comment]
This is done now.

**Comment by atoato88** [comment]
Thank you for fixing.
I'll look at the scores on the next day.

**Comment by atoato88** [comment]
I could get the latest score on k8s devstats!
Thank you for quick fix!

**Comment by lukaszgryglicki** [comment]
Great, thank you for reporting!
