### ISSUE TITLE
[bug] company-statistics-by-repository-group broken for k8s

### ISSUE THREAD

**Issue by dims** [cncf/devstats#41]
https://k8s.devstats.cncf.io/d/8/company-statistics-by-repository-group?orgId=1&var-period=q&var-metric=activity&var-repogroup_name=Kubernetes&var-repo_name=&var-companies=All&inspect=1&inspectTab=error

shows this failure

![image](https://github.com/cncf/devstats/assets/23304/07ac9a2e-ef43-4573-9d14-e37e61da82c4)

**Comment by lukaszgryglicki** [comment]
Fixed, thanks for reporting.

**Comment by dims** [comment]
@lukaszgryglicki same problem with another company ( same URL! https://k8s.devstats.cncf.io/d/8/company-statistics-by-repository-group?orgId=1 )

![image](https://github.com/cncf/devstats/assets/23304/c472e095-7772-43ed-ac09-b0ec4c8791fb)

**Comment by lukaszgryglicki** [comment]
Will TAL tomorrow.

**Comment by lukaszgryglicki** [comment]
Checking this.

**Comment by lukaszgryglicki** [comment]
I think I've found [a bug](https://github.com/cncf/devstatscode/commit/2c119427465b8c8cc6bb6071d62098e5a75cc2ff), now testing if that solves this for good...

**Comment by lukaszgryglicki** [comment]
It fixed this, @dims, the issue seemed to be that
```
schemaname = 'public' and substring(tablename from %s) is not null
```
when called with `%s` = `^scompany_activity(_repos)?$` was returning a hit for table `scompany_activity_repos` but not for `scompany_activity` which doesn't seem to be OK for me (the expression in `()?` should just be optional and it should hit both tables).

I've changed this to the `~` Postgres operator and it returns the correct hits now:
```
schemaname = 'public' and tablename ~ %s
```

Some tables were not returned as candidates to be updated with possible columns list, so the outcome was that columns were missing.

Hope it won't reappear...

**Comment by lukaszgryglicki** [comment]
Rechecked today
 (both the DB data and the dashboard) and it seems to be OK.

**Comment by lukaszgryglicki** [comment]
Rechecked once more after 2 weeks and it is still OK, so I'm assuming that this fixed it :)
