### ISSUE TITLE
[question]  can't find my name in Developer Activity Counts by Repository Group Table filtered by country

### ISSUE THREAD

**Issue by xiangpingjiang** [cncf/devstats#42]
I can find my name in this link  https://knative.devstats.cncf.io/d/9/developer-activity-counts-by-repository-group-table?orgId=1&var-period_name=Last%20decade&var-metric=merged_prs&var-repogroup_name=All&var-country_name=All ,  but not in this  link https://knative.devstats.cncf.io/d/9/developer-activity-counts-by-repository-group-table?orgId=1&var-period_name=Last%20decade&var-metric=merged_prs&var-repogroup_name=All&var-country_name=China .  I have already updated  my country info  to China in openprofile.dev.   Do you know the reason ?

**Comment by xiangpingjiang** [comment]
I need submit a pr to [gitdm](https://github.com/xiangpingjiang/gitdm)  to add my info ?

**Comment by lukaszgryglicki** [comment]
Yes please update your data in `gitdm`.

**Comment by xiangpingjiang** [comment]
> Yes please update your data in `gitdm`.

Thanks,  I can't find my info in github_users.json, should I add my info in this file first?

**Comment by lukaszgryglicki** [comment]
You don't need to - all you need is [described here](https://github.com/cncf/gitdm#addingupdating-affiliation). Everything else will be generated automatically.

**Comment by lukaszgryglicki** [comment]
Closing this, we need data in `cncf/gitdm` first, so this is not a bug, we just need data to be processed.

**Comment by xiangpingjiang** [comment]
@lukaszgryglicki 
Hello, I see that cncf/gitdm affiliations are imported into DevStats (cncf/devstats) once per 4 weeks, so when my info will be updated, thanks ?

**Comment by lukaszgryglicki** [comment]
On the next `k8s` affiliations sync which is:
```
root@devstats-node-2:~/go/src/github.com/cncf/devstats-k8s-lf/util# k get cj -A | grep affiliations-kubernetes
devstats-prod   devstats-affiliations-kubernetes                0 20 28 * *                               False     0        22d             2y332d
```

So it will start at 8:00 PM UTC on 11/28/2023.

Can you point me to your `cncf/gitdm` PR with your updates - so I will double check if it is merged and correctly reflected in cncf/gitdm and cncf/devstats data files - thsi si what gets imported by DevStats deployment once per 28 days.

**Comment by xiangpingjiang** [comment]
hello @lukaszgryglicki 
This is my pr https://github.com/cncf/gitdm/pull/225

**Comment by lukaszgryglicki** [comment]
Ok so it is merged & updated in `cncf/devstats` and `cncf/gitdm` (all files) which means it will be updated on 11/28/23 8 PM UTC as I daid [here](https://github.com/cncf/devstats/issues/42#issuecomment-1818955160).

**Comment by xiangpingjiang** [comment]
hello @lukaszgryglicki 
Now it's 11/29/23 UTC, I noticed that my info didn't be updated in cncf/devstats dashboard .  Is there a problem ?

**Comment by lukaszgryglicki** [comment]
I will check on Friday.

**Comment by lukaszgryglicki** [comment]
Last affiliations job was running 22 days ago for `knative` - its cron job definition is like this:
```
devstats-affiliations-knative                   23 8 8 * *
```

So it `would` run on 8th (sorry for the confusion - I was thinking you refer to kubernetes not Knative), anyway - I've run this manually now and your data was updated in the DB:
```
root@devstats-node-0:~# k exec -itn devstats-prod devstats-postgres-0 -- psql knative
psql (13.1 (Debian 13.1-1.pgdg100+1))
Type "help" for help.

knative=# select * from gha_actors where login = 'xiangpingjiang';
    id    |     login      | name | country_id | sex | sex_prob | tz | tz_offset | country_name | age 
----------+----------------+------+------------+-----+----------+----+-----------+--------------+-----
 45722758 | xiangpingjiang | cola | cn         |     |          |    |           | China        |    
(1 row)

knative=# select * from gha_actors_affiliations where actor_id in (select id from gha_actors where login = 'xiangpingjiang');
 actor_id | company_name | original_company_name |       dt_from       |        dt_to        | source 
----------+--------------+-----------------------+---------------------+---------------------+--------
 45722758 | Ant Group    | Ant Group             | 1900-01-01 00:00:00 | 2100-01-01 00:00:00 | user
(1 row)
```

And the TSDB data was alsso regenerated so [the dashboard](https://knative.devstats.cncf.io/d/9/developer-activity-counts-by-repository-group-table?orgId=1&var-period_name=Last%20decade&var-metric=merged_prs&var-repogroup_name=All&var-country_name=All) now shows you - 13 merged PRs, rank 182th.
@xiangpingjiang

**Comment by xiangpingjiang** [comment]
@lukaszgryglicki 
Thanks a lot , that's great. 
I have a another question, how to  count the merged PRs. Because I calculated that I have 15 merged PRs to all knative  repo group.

**Comment by lukaszgryglicki** [comment]
The dashboard is OK, regarding the data we have in the database:
```
knative=# select distinct dup_repo_name, number from gha_pull_requests where dup_user_login in (select login from gha_actors where login = 'xiangpingjiang') and dup_type = 'PullRequestEvent' and merged_at is not null order by 1, 2;
            dup_repo_name            | number 
-------------------------------------+--------
 knative/client                      |   1853
 knative/client                      |   1856
 knative/client                      |   1860
 knative/docs                        |   5673
 knative/docs                        |   5681
 knative/docs                        |   5686
 knative/eventing                    |   7244
 knative/eventing                    |   7338
 knative/eventing                    |   7417
 knative-extensions/kn-plugin-sample |    107
 knative/networking                  |    840
 knative/pkg                         |   2849
 knative/serving                     |  14565
(13 rows)
```
There is an ongoing issue with data missing on the GHA side: https://github.com/cncf/gitdm/issues/214#issuecomment-1818495908
