### ISSUE TITLE
[bug] Status of employer updates?

### ISSUE THREAD

**Issue by jberkus** [cncf/devstats#44]
Folks,

In the past, CNCF had a contractor who would go through the list of maintainers and contributors a couple times a year and try to fill in missing/changed data from people who had changed jobs.  Based on looking at contributor data, it seems like that process doesn't exist anymore?  I'm finding quite a few maintainers whose affiliation is more than a year out of date.

Relatedly, we should be able to obtain updated employment data through EasyCLA, for the CLA projects.  

What's the status of keeping this information up to date?

**Comment by lukaszgryglicki** [comment]
If there is nobody who will do it, I can check manually - LMK if this is needed and what file should I use for this.

**Comment by jberkus** [comment]
What I was trying to find out is whether we still had a contractor who was tasked with this.  Sounds like no?

**Comment by lukaszgryglicki** [comment]
Yes we have, but that contractor researches unknown contributors by number of contributions desc, I can ask her to check a very specific list/file where maintainers are and make sure all is updated in DevStats/gitdm. 
LMK if we need to do this (it was done at least a few times in the past) and which file shoudl she check @jberkus

**Comment by jberkus** [comment]
It's bigger than that, I want to look at ways to make the contractor's work faster, possibly by finding new data sources.  And possibly with a campaign to get CNCF members to update their own employee data.

**Comment by lukaszgryglicki** [comment]
OK, /sgtm

**Comment by lukaszgryglicki** [comment]
@jberkus PTAL https://github.com/cncf/devstats/issues/47#issuecomment-1867338017

**Comment by lukaszgryglicki** [comment]
I'm closing this, please reopen if needed.
