### ISSUE TITLE
[bug] Knative "New Contributors Table" is broken

### ISSUE THREAD

**Issue by aliok** [cncf/devstats#46]
Context: We want to [recognize](https://github.com/knative/community/issues/1473) new contributors in Knative and folks from Cilium told us that they're using Devstats (among other things) for this purpose.

There's this table for Cilium: https://cilium.devstats.cncf.io/d/52/new-contributors-table?orgId=1

Here's the table for Knative: https://knative.devstats.cncf.io/d/52/new-contributors-table?orgId=1

The Knative table looks broken though.

Thanks for your support!

**Comment by lukaszgryglicki** [comment]
Fixed "temporarily" - I'll fix permamently when I have some time - probably on Friday. Thanks for reporting.

**Comment by lukaszgryglicki** [comment]
Fixed permamently by creating a new docker image with updated dashbard, closing.
