### ISSUE TITLE
[bug] Profile not showing

### ISSUE THREAD

**Issue by AmbrishRamachandiran** [cncf/devstats#49]
Hi i have made 15+ contributions (merged) to backstage community [PR](https://github.com/backstage/backstage/pulls?q=is%3Apr+author%3AAmbrishRamachandiran+is%3Aclosedl) .

for the organization infosys , my github profile [PROFILE](https://github.com/AmbrishRamachandiran)/

But my contributions or not showing in grafana reports [Developer activity by company](https://backstage.devstats.cncf.io/d/66/developer-activity-counts-by-companies?orgId=1&var-period_name=Last%20decade&var-metric=contributions&var-repogroup_name=All&var-country_name=All&var-companies=Infosys%20Limited)

**Comment by lukaszgryglicki** [comment]
Hi, I'm on PTO until 1/30/24, I'll TAL when I'm back.

**Comment by AmbrishRamachandiran** [comment]
@lukaszgryglicki any suggestions on this issue?

**Comment by lukaszgryglicki** [comment]
https://github.com/cncf/devstats/issues/49#issuecomment-1896049852

**Comment by lukaszgryglicki** [comment]
Your GH id affiliations aren't imported yet - meybe they were added/updated less than 28 days ago? Affiliations are imported once per 4 weeks - I'll do it manually now.

**Comment by lukaszgryglicki** [comment]
```
backstage=# select * from gha_actors where lower(login) = 'ambrishramachandiran';
    id     |        login         | name | country_id | sex | sex_prob | tz | tz_offset | country_name | age 
-----------+----------------------+------+------------+-----+----------+----+-----------+--------------+-----
 133481507 | AmbrishRamachandiran |      |            |     |          |    |           |              |    
(1 row)

backstage=# select * from gha_actors_affiliations where actor_id in (select id from gha_actors where lower(login) = 'ambrishramachandiran');
 actor_id | company_name | original_company_name | dt_from | dt_to | source 
----------+--------------+-----------------------+---------+-------+--------
(0 rows)

backstage=# 
```

**Comment by AmbrishRamachandiran** [comment]
> Your GH id affiliations aren't imported yet - meybe they were added/updated less than 28 days ago? Affiliations are imported once per 4 weeks - I'll do it manually now.

@lukaszgryglicki  you mean this is enough ? ->  https://github.com/cncf/gitdm/pull/258

**Comment by lukaszgryglicki** [comment]
It was merged 3 hours ago - so it's not reflected yet in ANY dashboard.
But I'm updating manually just 4u.

**Comment by AmbrishRamachandiran** [comment]
> It was merged 3 hours ago - so it's not reflected yet in ANY dashboard. But I'm updating manually just 4u.

Thanks much for your kind help , can you please include this too manually ->  **krishnakv : krishna_kumar08!@infosys.com	
        Infosys Limited**

**Comment by lukaszgryglicki** [comment]
I'm importing & regenerating all, so that one will be included as well:
```
backstage=# select * from gha_actors_affiliations where actor_id in (select id from gha_actors where lower(login) = 'ambrishramachandiran');
 actor_id  |  company_name   | original_company_name |       dt_from       |        dt_to        | source 
-----------+-----------------+-----------------------+---------------------+---------------------+--------
 133481507 | Infosys Limited | Infosys Limited       | 1900-01-01 00:00:00 | 2100-01-01 00:00:00 | user
(1 row)

backstage=# select * from gha_actors_affiliations where actor_id in (select id from gha_actors where lower(login) = 'krishnakv');
      actor_id       |  company_name   | original_company_name |       dt_from       |        dt_to        | source 
---------------------+-----------------+-----------------------+---------------------+---------------------+--------
 -202721519059204160 | Infosys Limited | Infosys Limited       | 1900-01-01 00:00:00 | 2100-01-01 00:00:00 | user
(1 row)

backstage=# 


```

**Comment by lukaszgryglicki** [comment]
Data updated - now you can see 50 PRs that you've authored: [click](https://backstage.devstats.cncf.io/d/66/developer-activity-counts-by-companies?orgId=1&var-period_name=Last%20decade&var-metric=prs&var-repogroup_name=All&var-country_name=All&var-companies=Infosys%20Limited).
Closing.

**Comment by AmbrishRamachandiran** [comment]
[Developer Activity Counts by Companies](https://all.devstats.cncf.io/d/66/developer-activity-counts-by-companies?var-period_name=Last%20decade&var-metric=contributions&var-repogroup_name=All&var-country_name=All&var-companies=Infosys%20Limited) 
 
 In over all cncf still my profile is not visible any possible reason?
