### ISSUE TITLE
[bug] Armada devstats link doesn't work

### ISSUE THREAD

**Issue by kannon92** [cncf/devstats#6]
Hello, I wanted to take a look at devstats and I notice that Armada doesn't work.  

https://armada.devstats.cncf.io/

Not sure if this is the right place but can someone point me into the direction to fix this?

**Comment by lukaszgryglicki** [comment]
Hmmm I'm not able to replicate it, when I click that link I can see DevStats, see screenshot:
![Uploading Zrzut ekranu 2023-05-10 o 16.20.48.png…]()

**Comment by kannon92** [comment]
Interesting..  Maybe it was just temp down when I checked.

**Comment by lukaszgryglicki** [comment]
I also wonder what was it, I don't see anything failed like cronjobs/grafanas/sync, etc.
