### ISSUE TITLE
Updated Dumps

### ISSUE THREAD

**Issue by germonprez** [cncf/devstats#61]
Hi, 

There are a few database dumps that are a bit old (2021/2022) -- examples here: 

prometheus.dump
buildpacks.dump
distribution.dump
inclavarecontainers.dump
k3s.dump
k8dash.dump
karmada.dump
opentracing.dump 
virtualkubelet.dump 
wasmcloud.dump 

Could someone provide a bit of detail on why some are older and/or if they might be updated? 

Thanks in advance! I really appreciate any help.

**Comment by lukaszgryglicki** [comment]
I can take a look next week after my PTO.
Are you talking about `teststats` instances or `devstats` instances?
Please provide a link to one such example and I'll check this.

**Comment by germonprez** [comment]
Thanks. I'm referring to: https://devstats.cncf.io/backups/

**Comment by lukaszgryglicki** [comment]
OK will check next week and eventually manually regenerate.

**Comment by lukaszgryglicki** [comment]
Update: I may check on Friday, but due to a lot of work accumulation during my PTO this can be postponed a bit - but this is on my dashboard FYI.

**Comment by germonprez** [comment]
No problem. Thanks for the update.

**Comment by lukaszgryglicki** [comment]
Checking this.

**Comment by lukaszgryglicki** [comment]
I'm updating others, but for `opentracing` there will be no newer backup as it is an archived and no longer tracked project.

**Comment by lukaszgryglicki** [comment]
Dumps updated, there is no single non-archived project dump that is older than 2024 now.
Closing, pls reopen if needed.

**Comment by germonprez** [comment]
Thank you!
