### ISSUE TITLE
[bug] "last decade" option no longer large enough to show entire history

### ISSUE THREAD

**Issue by BenTheElder** [cncf/devstats#70]
Please add something longer now that we're past https://events.linuxfoundation.org/kuber10es-birthday-bash/ :-)

**Comment by lukaszgryglicki** [comment]
Due to volume of data that we need to process I woudl rather change "last 10 years/decade" to "All time" - is this OK?
cc @caniszczyk

**Comment by BenTheElder** [comment]
I'm personally OK with that, to me "last decade" was a placeholder for "all time" since nothing had been going on for a decade yet ... but I don't know if that's suitable for other users ... one thought is it might break incoming links?

EDIT: Also I'm actually just pleased that we've come far enough that we're running into problems like "a decade isn't the entire history anymore" :-)

I had joked about this with @onlydole at the birthday bash and forgot to follow up and actually suggest doing something about this until now 😅 

Replacing "last decade" with "all time" sounds reasonable to me.

**Comment by lukaszgryglicki** [comment]
Actually u r right, lest's not change something that is already there and might be used.
I will just add a "all time" range - internally I need to have date from and date to (to avoid rebuilding a lot of code) so I will make it "last century" :P.

**Comment by lukaszgryglicki** [comment]
Code is updated, now I'm generating this new time range for all tabular metrics in Kubernetes project.

**Comment by lukaszgryglicki** [comment]
Finished, K8s DevStats instance now has "Last century" option. Closing, please reopen if needed.

**Comment by BenTheElder** [comment]
Thanks!
