### ISSUE TITLE
[bug] Rename Notary V2 to notaryproject/notation

### ISSUE THREAD

**Issue by FeynmanZhou** [cncf/devstats#8]
Hi team

I am a Notary maintainer. Could you rename `Notary V2` to `notaryproject/notation` at https://notary.devstats.cncf.io/? We no longer use Notary v2 for that repo name. This is the corresponding repo in the Notary project: https://github.com/notaryproject/notation

![image](https://github.com/cncf/devstats/assets/40452856/bd87aa8d-a912-4ed9-bcc5-83096e862fbd)

**Comment by lukaszgryglicki** [comment]
This is just to change the Repo Group name, right? No need to delete anything or add any new orgs, etc.? I will work on this tomorrow.

**Comment by lukaszgryglicki** [comment]
On it.

**Comment by lukaszgryglicki** [comment]
This is done. Closing.
