### ISSUE TITLE
[Bug][Kubernetes] Query error prevents company repo specific stats from being displayed

### ISSUE THREAD

**Issue by mrbobbytables** [cncf/devstats#9]
Dashboard: https://k8s.devstats.cncf.io/d/8/company-statistics-by-repository-group?orgId=1&viewPanel=4
Error: `db query error: pq: column "Starbucks Corporation" does not exist`

I haven't stumbled across others, but it might impact some other dashboards as well.

**Comment by lukaszgryglicki** [comment]
Checking this.

**Comment by lukaszgryglicki** [comment]
This is fixed, closing, thanks for reporting.
